In [1]:
import numpy as np

In [10]:
left = np.array([[1,0,0,1,0],[4,1,0,0,1],[5,4,1,0,0],[0,5,4,0,0],[0,0,5,0,0]])
right = np.array([0,0,0,0,25])

In [11]:
left

array([[1, 0, 0, 1, 0],
       [4, 1, 0, 0, 1],
       [5, 4, 1, 0, 0],
       [0, 5, 4, 0, 0],
       [0, 0, 5, 0, 0]])

In [12]:
right

array([ 0,  0,  0,  0, 25])

In [15]:
sol= np.linalg.solve(left,right)

In [16]:
sol

array([ 2.2, -4. ,  5. , -2.2, -4.8])

In [18]:
5*sol

array([ 11., -20.,  25., -11., -24.])